name: Auth CI

on:
  push:
    branches:
      - main

env:
  ECR_REPOSITORY: auth
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag and Push Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
            $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          docker tag $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            $REGISTRY/$ECR_REPOSITORY:latest

          docker push $REGISTRY/$ECR_REPOSITORY:latest