name: Auth CI

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: auth
  ECR_REGISTRY: 137307166466.dkr.ecr.ap-south-1.amazonaws.com

  PORT: 4001
  JWT_SECRET: health-check-app
  DB_HOST: postgresql.postgresql
  DB_PORT: 5432
  DB_NAME: microservice_auth
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_POOL_MAX: 10

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat > .env << EOF
          PORT=${PORT}
          JWT_SECRET=${JWT_SECRET}
          DB_HOST=${DB_HOST}
          DB_PORT=${DB_PORT}
          DB_NAME=${DB_NAME}
          DB_USER=${DB_USER}
          DB_PASSWORD=${DB_PASSWORD}
          DB_POOL_MAX=${DB_POOL_MAX}
          EOF

      - name: Verify .env
        run: cat .env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} .

      - name: Tag Docker Image
        run: |
          docker tag $ECR_REPOSITORY:${{ github.sha }} \
          $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

          docker tag $ECR_REPOSITORY:${{ github.sha }} \
          $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Push Docker Images
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Verify Image
        run: |
          echo "Successfully pushed:"
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}"
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:latest"